"""Replace the weights: block in config.yaml with the user's hand-tuned values.

Preserves all other top-level sections (position_groups, invert_metrics,
metric_categories, distribution_metrics_by_position, xt_grid) and header
comments.

Backs up to config.yaml.user-pre.bak before writing.
"""
import shutil
from pathlib import Path
from ruamel.yaml import YAML
from ruamel.yaml.comments import CommentedMap

HERE = Path(__file__).parent
CFG = HERE / "config.yaml"
BAK = HERE / "config.yaml.user-pre.bak"

USER_WEIGHTS = {
    "Shot Stopper": {
        "goalsPrevented": 4.0,
        "goalsPreventedPerSOT": 4.0,
        "goalsConceded": 1.0,
        "exits": 1.0,
        "Passes successful %": 1.0,
        "Long passes successful %": 1.0,
        "passes_gk": 1.0,
        "recoveries_gk": 1.0,
        "GK_Shotstopping_per_90": 12.0,
        "GK_Handling_per_90": 5.0,
        "GK_Sweeping_per_90": 1.0,
        "Passing_per_90": 1.0,
    },
    "Cross Claimer": {
        "goalsPrevented": 2.0,
        "goalsPreventedPerSOT": 2.0,
        "goalsConceded": 1.0,
        "exits": 6.0,
        "Passes successful %": 1.0,
        "longPassesSuccessful_gk": 1,
        "passes_gk": 1.0,
        "recoveries_gk": 10,
        "GK_Shotstopping_per_90": 6.0,
        "GK_Handling_per_90": 6.0,
        "GK_Sweeping_per_90": 15.0,
        "Passing_per_90": 1.0,
    },
    "Ball-playing GK": {
        "goalsPrevented": 2.0,
        "goalsPreventedPerSOT": 2.0,
        "goalsConceded": 1.0,
        "exits": 2.0,
        "Passes successful %": 4.0,
        "longPassesSuccessful_gk": 6.0,
        "passes_gk": 8.0,
        "recoveries_gk": 1.0,
        "GK_Shotstopping_per_90": 1.0,
        "GK_Handling_per_90": 1.0,
        "GK_Sweeping_per_90": 6.0,
        "Passing_per_90": 12.0,
    },
    "Ball-Playing Centerback": {
        "npxG": 1.0,
        "xAOP": 1.0,
        "xTOP": 20,
        "Passes": 20,
        "Passes successful %": 6,
        "Progressive Passes": 20,
        "Progressive runs": 6,
        "Aerial duels": 2,
        "Aerial duels successful %": 6,
        "Aerial duels att box successful": 1,
        "Defensive duels": 2,
        "Defensive duels successful %": 8,
        "Interceptions": 6,
        "Recoveries": 6,
        "Clearances": 2,
        "Avg defensive action height": 1,
        "Defensive Area": 1,
        "Territorial Dominance OE": 2,
        "Opp xT into Def Area OE": 1,
        "Opp xT from Def Area OE": 1,
        "Shooting_per_90": 1.0,
        "Passing_per_90": 30.0,
        "Receiving_per_90": 1.0,
        "Dribbling_per_90": 10.0,
        "SetPiece_per_90": 1.0,
        "Interrupting_per_90": 10.0,
    },
    "Stopper": {
        "npxG": 3.0,
        "xAOP": 0,
        "xTOP": 1.0,
        "Passes": 1.0,
        "Passes successful %": 1.0,
        "Progressive Passes": 1.0,
        "Progressive runs": 1.0,
        "Aerial duels": 8,
        "Aerial duels successful %": 10,
        "Aerial duels att box successful": 2,
        "Defensive duels": 8,
        "Defensive duels successful %": 10,
        "Interceptions": 8,
        "Recoveries": 8,
        "Clearances": 3,
        "Avg defensive action height": 0,
        "Defensive Area": 2,
        "Territorial Dominance OE": 8,
        "Opp xT into Def Area OE": 4,
        "Opp xT from Def Area OE": 4,
        "Shooting_per_90": 1.0,
        "Passing_per_90": 3.0,
        "Receiving_per_90": 1.0,
        "Dribbling_per_90": 1.0,
        "SetPiece_per_90": 1.0,
        "Interrupting_per_90": 20.0,
    },
    "Athletic Centerback": {
        "npxG": 4.0,
        "xAOP": 0,
        "xTOP": 1.0,
        "Passes": 1.0,
        "Passes successful %": 1.0,
        "Progressive Passes": 1.0,
        "Progressive runs": 4,
        "Aerial duels": 5,
        "Aerial duels successful %": 10,
        "Aerial duels att box successful": 6,
        "Defensive duels": 5,
        "Defensive duels successful %": 10,
        "Interceptions": 10,
        "Recoveries": 8,
        "Clearances": 2,
        "Avg defensive action height": 1,
        "Defensive Area": 10,
        "Territorial Dominance OE": 14,
        "Opp xT into Def Area OE": 8,
        "Opp xT from Def Area OE": 2,
        "Shooting_per_90": 2.0,
        "Passing_per_90": 6.0,
        "Receiving_per_90": 1.0,
        "Dribbling_per_90": 4.0,
        "SetPiece_per_90": 1.0,
        "Interrupting_per_90": 16.0,
    },
    "Box-to-Box": {
        "Passes": 4,
        "Passes successful %": 3,
        "Progressive Passes": 2,
        "xTOP": 4.0,
        "Goals": 1.0,
        "npxG": 4,
        "Shots": 2,
        "xG per Shot": 1.0,
        "Assists": 1.0,
        "xAOP": 4,
        "Progressive runs": 5,
        "Dribbles successful": 4,
        "Aerial duels successful": 1.0,
        "Defensive duels successful": 2,
        "Interceptions": 3,
        "Recoveries": 4,
        "Shooting_per_90": 6.0,
        "Passing_per_90": 10.0,
        "Receiving_per_90": 6.0,
        "Dribbling_per_90": 8.0,
        "SetPiece_per_90": 1.0,
        "Interrupting_per_90": 8.0,
    },
    "Holding Mid": {
        "Passes": 4,
        "Passes successful %": 4,
        "Progressive Passes": 2,
        "xTOP": 4.0,
        "npxG": 1.0,
        "xAOP": 1.0,
        "Progressive runs": 1.0,
        "Dribbles successful": 1.0,
        "Aerial duels successful": 4,
        "Defensive duels successful": 6,
        "Interceptions": 6,
        "Recoveries": 6,
        "Shooting_per_90": 1.0,
        "Passing_per_90": 10.0,
        "Receiving_per_90": 1.0,
        "Dribbling_per_90": 1.0,
        "SetPiece_per_90": 1.0,
        "Interrupting_per_90": 12.0,
    },
    "Ball-Winning Mid": {
        "Passes": 4,
        "Passes successful %": 6,
        "Progressive Passes": 2,
        "xTOP": 2.0,
        "npxG": 1.0,
        "xAOP": 1.0,
        "Progressive runs": 1.0,
        "Aerial duels": 4,
        "Aerial duels successful %": 6,
        "Defensive duels": 6,
        "Defensive duels successful %": 10,
        "Interceptions": 10,
        "Recoveries": 10,
        "Recoveries Opp Half": 4,
        "Shooting_per_90": 1.0,
        "Passing_per_90": 6.0,
        "Receiving_per_90": 1.0,
        "Dribbling_per_90": 1.0,
        "SetPiece_per_90": 1.0,
        "Interrupting_per_90": 14.0,
    },
    "Deep-lying Playmaker": {
        "Passes": 10,
        "Passes successful %": 6,
        "Progressive Passes": 10,
        "Passes to final third successful": 8,
        "xTOP": 10,
        "npxG": 1.0,
        "xAOP": 8,
        "Progressive runs": 2,
        "Dribbles successful": 1.0,
        "Aerial duels successful": 1.0,
        "Defensive duels successful": 4,
        "Interceptions": 4,
        "Recoveries": 6,
        "Shooting_per_90": 1.0,
        "Passing_per_90": 25.0,
        "Receiving_per_90": 5.0,
        "Dribbling_per_90": 4.0,
        "SetPiece_per_90": 1.0,
        "Interrupting_per_90": 6.0,
    },
    "Advanced Playmaker": {
        "Passes": 6,
        "Passes successful %": 2,
        "Progressive Passes": 4,
        "xTOP": 8,
        "Goals": 2,
        "npxG": 8,
        "Shots": 2,
        "xG per Shot": 2,
        "Assists": 2,
        "xAOP": 8,
        "Progressive runs": 2,
        "Dribbles successful": 2,
        "Aerial duels successful": 1.0,
        "Defensive duels successful": 1.0,
        "Interceptions": 1.0,
        "Recoveries": 1.0,
        "Counterpressing Recoveries": 1,
        "Shooting_per_90": 10.0,
        "Passing_per_90": 20.0,
        "Receiving_per_90": 10.0,
        "Dribbling_per_90": 8.0,
        "SetPiece_per_90": 1.0,
        "Interrupting_per_90": 1.0,
    },
    "Full Back": {
        "npxG": 4,
        "xAOP": 4,
        "xTOP": 3,
        "Passes": 2,
        "Passes successful %": 2,
        "Progressive Passes": 2,
        "Progressive runs": 2,
        "Aerial duels": 2,
        "Aerial duels successful %": 8,
        "Defensive duels": 4,
        "Defensive duels successful %": 10,
        "Interceptions": 8,
        "Recoveries": 8,
        "Clearances": 2,
        "Avg defensive action height": 0,
        "Shooting_per_90": 4.0,
        "Passing_per_90": 16.0,
        "Receiving_per_90": 4.0,
        "Dribbling_per_90": 8.0,
        "SetPiece_per_90": 1.0,
        "Interrupting_per_90": 16.0,
    },
    "Wingback": {
        "Goals": 2,
        "npxG": 4,
        "Shots": 2,
        "xG per Shot": 1,
        "Assists": 6,
        "xAOP": 8,
        "xTOP": 6,
        "Passes": 1.0,
        "Passes successful %": 1.0,
        "Progressive Passes": 2,
        "Crosses successful": 2,
        "Progressive runs": 3,
        "Aerial duels": 1.0,
        "Aerial duels successful %": 1.0,
        "Defensive duels": 1.0,
        "Defensive duels successful %": 4,
        "Interceptions": 4,
        "Recoveries": 4,
        "Clearances": 1.0,
        "Avg defensive action height": 0,
        "Shooting_per_90": 10.0,
        "Passing_per_90": 20.0,
        "Receiving_per_90": 10.0,
        "Dribbling_per_90": 14.0,
        "SetPiece_per_90": 3.0,
        "Interrupting_per_90": 5.0,
    },
    "Inverted Full Back": {
        "npxG": 1.0,
        "xAOP": 1.0,
        "xTOP": 12,
        "Passes": 16,
        "Passes successful %": 6,
        "Progressive Passes": 8,
        "Progressive runs": 2,
        "Aerial duels": 1.0,
        "Aerial duels successful %": 4,
        "Defensive duels": 4,
        "Defensive duels successful %": 6,
        "Interceptions": 6,
        "Recoveries": 4,
        "Clearances": 1.0,
        "Avg defensive action height": 0,
        "Shooting_per_90": 6.0,
        "Passing_per_90": 30.0,
        "Receiving_per_90": 10.0,
        "Dribbling_per_90": 10.0,
        "SetPiece_per_90": 1.0,
        "Interrupting_per_90": 10.0,
    },
    "Wide Winger": {
        "Goals": 4,
        "npxG": 8,
        "Shots": 2,
        "xG per Shot": 2,
        "Assists": 4,
        "xAOP": 8,
        "xTOP": 6,
        "Passes": 1.0,
        "Passes successful %": 1.0,
        "Progressive Passes": 1.0,
        "Deep Completions": 2,
        "Crosses successful": 2,
        "Progressive runs": 2,
        "Dribbles": 4,
        "Dribbles successful %": 2,
        "Loss index": 5,
        "Aerial duels successful": 1.0,
        "Defensive duels successful": 1.0,
        "Interceptions": 1.0,
        "Recoveries": 1.0,
        "Counterpressing Recoveries": 1,
        "Shooting_per_90": 10.0,
        "Passing_per_90": 16.0,
        "Receiving_per_90": 10.0,
        "Dribbling_per_90": 14.0,
        "SetPiece_per_90": 1.0,
        "Interrupting_per_90": 1.0,
    },
    "Creative Winger": {
        "Goals": 4,
        "npxG": 8,
        "Shots": 2,
        "xG per Shot": 2,
        "Assists": 6,
        "xAOP": 12,
        "xTOP": 10,
        "Passes": 2,
        "Passes successful %": 1.0,
        "Progressive Passes": 2,
        "Deep Completions": 3,
        "Crosses successful": 2,
        "Progressive runs": 2,
        "Dribbles": 2,
        "Dribbles successful %": 4,
        "Loss index": 5,
        "Aerial duels successful": 1.0,
        "Defensive duels successful": 1.0,
        "Interceptions": 1.0,
        "Recoveries": 1.0,
        "Counterpressing Recoveries": 1,
        "Shooting_per_90": 14.0,
        "Passing_per_90": 20.0,
        "Receiving_per_90": 12.0,
        "Dribbling_per_90": 12.0,
        "SetPiece_per_90": 1.0,
        "Interrupting_per_90": 1.0,
    },
    "Inside Forward": {
        "Goals": 15,
        "npxG": 30,
        "Shots": 6,
        "xG per Shot": 8,
        "Assists": 10,
        "xAOP": 20,
        "xTOP": 2,
        "Passes": 1.0,
        "Passes successful %": 1.0,
        "Progressive runs": 2,
        "Dribbles": 4,
        "Dribbles successful %": 4,
        "Loss index": 5,
        "Aerial duels successful": 4,
        "Defensive duels successful": 1.0,
        "Interceptions": 1.0,
        "Recoveries": 1.0,
        "Counterpressing Recoveries": 1,
        "Shooting_per_90": 30.0,
        "Passing_per_90": 10.0,
        "Receiving_per_90": 30.0,
        "Dribbling_per_90": 10.0,
        "SetPiece_per_90": 1.0,
        "Interrupting_per_90": 1.0,
    },
    "Shadow Striker": {
        "Goals": 15,
        "npxG": 30,
        "Shots": 10,
        "xG per Shot": 8,
        "Assists": 10,
        "xAOP": 20,
        "xTOP": 4,
        "Passes": 2,
        "Passes successful %": 2,
        "Progressive Passes": 3,
        "Deep Completions": 3,
        "Progressive runs": 2,
        "Dribbles": 4,
        "Dribbles successful %": 4,
        "Loss index": 5,
        "Aerial duels successful": 2,
        "Defensive duels successful": 1.0,
        "Interceptions": 1.0,
        "Recoveries": 3,
        "Shooting_per_90": 30.0,
        "Passing_per_90": 20.0,
        "Receiving_per_90": 20.0,
        "Dribbling_per_90": 14.0,
        "SetPiece_per_90": 1.0,
        "Interrupting_per_90": 1.0,
    },
    "Mobile Striker": {
        "Goals": 15,
        "npxG": 30,
        "Shots": 10,
        "xG per Shot": 8,
        "Assists": 10,
        "xAOP": 20,
        "xTOP": 4,
        "Passes": 2,
        "Passes successful %": 1.0,
        "Progressive Passes": 1.0,
        "Deep Completions": 1.0,
        "Progressive runs": 8,
        "Dribbles": 8,
        "Dribbles successful %": 6,
        "Loss index": 5,
        "Aerial duels": 1.0,
        "Aerial duels successful %": 1.0,
        "Defensive duels successful": 1.0,
        "Interceptions": 1.0,
        "Recoveries": 6,
        "Shooting_per_90": 30.0,
        "Passing_per_90": 20.0,
        "Receiving_per_90": 20.0,
        "Dribbling_per_90": 20.0,
        "SetPiece_per_90": 1.0,
        "Interrupting_per_90": 1.0,
    },
    "Poacher": {
        "Goals": 20,
        "npxG": 40,
        "Shots": 10,
        "xG per Shot": 10,
        "Assists": 10,
        "xAOP": 20,
        "Passes": 1.0,
        "Passes successful %": 1.0,
        "Progressive Passes": 1.0,
        "Deep Completions": 1.0,
        "Progressive runs": 1.0,
        "Dribbles successful": 1.0,
        "Loss index": 5,
        "Aerial duels": 5,
        "Aerial duels successful %": 5,
        "Defensive duels successful": 1.0,
        "Interceptions": 1.0,
        "Recoveries": 1.0,
        "Shooting_per_90": 40.0,
        "Passing_per_90": 6.0,
        "Receiving_per_90": 30.0,
        "Dribbling_per_90": 6.0,
        "SetPiece_per_90": 1.0,
        "Interrupting_per_90": 1.0,
    },
    "Target Man": {
        "Goals": 15,
        "npxG": 30,
        "Shots": 10,
        "xG per Shot": 8,
        "Assists": 10,
        "xAOP": 20,
        "xTOP": 2,
        "Passes": 2,
        "Passes successful %": 2,
        "Progressive Passes": 1.0,
        "Deep Completions": 1.0,
        "Progressive runs": 1.0,
        "Dribbles": 1.0,
        "Dribbles successful %": 1.0,
        "Loss index": 5,
        "Aerial duels": 10,
        "Aerial duels successful %": 10,
        "Defensive duels successful": 1.0,
        "Interceptions": 1.0,
        "Recoveries": 1.0,
        "Clearances": 10,
        "Shooting_per_90": 30.0,
        "Passing_per_90": 10.0,
        "Receiving_per_90": 20.0,
        "Dribbling_per_90": 8.0,
        "SetPiece_per_90": 1.0,
        "Interrupting_per_90": 3.0,
    },
    "Pressing Forward": {
        "Goals": 15,
        "npxG": 30,
        "Shots": 10,
        "xG per Shot": 8,
        "Assists": 10,
        "xAOP": 20,
        "xTOP": 2,
        "Passes": 2,
        "Passes successful %": 1.0,
        "Progressive Passes": 1.0,
        "Deep Completions": 1.0,
        "Progressive runs": 2,
        "Dribbles": 2,
        "Dribbles successful %": 2,
        "Loss index": 5,
        "Aerial duels": 1.0,
        "Aerial duels successful %": 1.0,
        "Defensive duels successful": 1.0,
        "Interceptions": 8,
        "Recoveries": 10,
        "Counterpressing Recoveries": 4,
        "Shooting_per_90": 30.0,
        "Passing_per_90": 20.0,
        "Receiving_per_90": 20.0,
        "Dribbling_per_90": 20.0,
        "SetPiece_per_90": 1.0,
        "Interrupting_per_90": 30.0,
    },
}


def main() -> None:
    if not BAK.exists():
        shutil.copy(CFG, BAK)
        print(f"Backed up {CFG.name} → {BAK.name}")

    yaml = YAML()
    yaml.preserve_quotes = True
    yaml.indent(mapping=2, sequence=4, offset=2)
    yaml.width = 200

    with open(CFG) as f:
        cfg = yaml.load(f)

    # Replace the whole weights block with user's values while preserving
    # the CommentedMap type so surrounding comments stay intact.
    new_weights = CommentedMap()
    for role, w in USER_WEIGHTS.items():
        role_map = CommentedMap()
        for k, v in w.items():
            role_map[k] = v
        new_weights[role] = role_map
    cfg["weights"] = new_weights

    with open(CFG, "w") as f:
        yaml.dump(cfg, f)

    n_roles = len(USER_WEIGHTS)
    n_keys = sum(len(w) for w in USER_WEIGHTS.values())
    print(f"Wrote {CFG.name} with user-tuned weights: {n_roles} roles, {n_keys} total weight keys")


if __name__ == "__main__":
    main()
