#!/usr/bin/env python3
"""Unified engine export for the dashboard (Phase A surfacing).

Denormalizes the rating/projection/duel/role outputs into ONE
player-season table so app.py needs a single cached loader instead of
six joins. Regenerated by scripts/rebuild_all.sh after the conversion
step; app code never needs to change when the engine version bumps.

Outputs:
  player_engine.parquet      one row per rated player-season
  player_engine_meta.json    {data_through, rating_version,
                              projection_version, built_at, n_rows}

Run from the Dashboard dir: python models/ratings/build_player_engine.py
"""
from datetime import datetime
import json
from pathlib import Path

import pandas as pd

_HERE = Path(__file__).resolve().parent
_DASH = _HERE.parent.parent

print("[1/4] rating + projection…", flush=True)
r = pd.read_parquet(_HERE / 'acp_rating_per_player_season.parquet')
p = pd.read_parquet(_HERE / 'acp_projection.parquet')
proj_cols = ['playerId', 'seasonId', 'age', 'career_asof', 'age_delta',
              'w_evidence', 'projection', 'projection_abs', 'band_sd',
              'proj_delta', 'seasons_ago']
# projection covers current-season rows + lapsed (24/25, no current row);
# lapsed rows join onto their LAST rated season's rating row.
eng = r.merge(p[proj_cols], on=['playerId', 'seasonId'], how='left')

print("[2/4] teams + duel ladders…", flush=True)
pt = pd.read_parquet(_HERE / 'player_teams.parquet')
eng = eng.merge(pt, on=['playerId', 'seasonId'], how='left')
duels = pd.read_parquet(_DASH / 'models/duels/duel_ratings.parquet')
duels = duels[duels['playerId'] > 0]
for trait in ['aerial', 'takeon', 'stopper', 'shield', 'press']:
    t = duels[duels['trait'] == trait].set_index('playerId')
    eng[f'duel_{trait}'] = eng['playerId'].map(t['rating'])
    eng[f'duel_{trait}_rd'] = eng['playerId'].map(t['rd'])
    eng[f'duel_{trait}_n'] = eng['playerId'].map(t['n'])

print("[3/4] data-through stamp…", flush=True)
# latest match date actually inside the engine = matches with lineup
# intervals (the rating's minute source)
iv = pd.read_parquet(_HERE / 'player_match_intervals.parquet',
                       columns=['matchId'])
ms = pd.read_parquet(_DASH / 'matches_summary.parquet',
                       columns=['matchId', 'dateutc'])
dates = pd.to_datetime(
    ms[ms['matchId'].isin(iv['matchId'].unique())]['dateutc'],
    errors='coerce')
data_through = str(dates.max().date())

print("[4/4] write…", flush=True)
eng.to_parquet(_HERE / 'player_engine.parquet')
meta = {
    'data_through': data_through,
    'rating_version': str(r['rating_version'].iloc[0]),
    'projection_version': str(p['projection_version'].iloc[0]),
    'built_at': datetime.now().strftime('%Y-%m-%d %H:%M'),
    'n_rows': int(len(eng)),
}
(_HERE / 'player_engine_meta.json').write_text(json.dumps(meta, indent=2))
print(f"  player_engine.parquet: {len(eng):,} rows x {len(eng.columns)} cols")
print(f"  meta: {meta}")
